### ISSUE TITLE
After installation it is giving me error as below.

### ISSUE THREAD

**Issue by Jaxterax** [R0X4R/Garud#18]
After installation I have just run the command like 

Garud -d target.com -f target

Error output 
[FTL] Could not create output file 'vulnerabilities/target-takeovers.txt': open vulnerabilities/target-takeovers.txt: no such file or directory

Why is it showing me error like this?

**Comment by R0X4R** [comment]
Hii @Jaxterax,
Greetings of the day.

I think your target is not vulnerable to subdomain-takeovers so that's why nuclei is throwing this error. If you get the error again do let me know also please attach the screenshot with it you can hide your target details ;). As for now, I'm closing this.

Thanks
