### ISSUE TITLE
Error : xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option

### ISSUE THREAD

**Issue by simrotion13** [R0X4R/Garud#24]
Output: /root/recon/output
 Threads: 100

xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
 ● Scanning is in progress: Scanning for vulnerabilities of example.com using nuclei [89%]

**Comment by R0X4R** [comment]
Hii @simrotion13,
Thanks for raising this issue.

This happened because your parameters file contains special characters like ``' ( )`` so ``xargs`` is throwing this error I have pushed the [update](https://github.com/R0X4R/Garud/commit/fe45784d1f67f1f5cbadf978ce58515ae8afd515). Please update your Garud.

Thanks and regards,
R0X4R
